### ISSUE TITLE
Plan the initial (CRAN) release

### ISSUE THREAD

**Issue by amoeba** [NCEAS/rt#25]
Hey @isteves I took a look over things, though I didn't run any code just yet. I pushed some stuff to https://github.com/NCEAS/rt/tree/minor-stuff, see https://github.com/NCEAS/rt/compare/master...minor-stuff. I otherwise looked at what's there now and had some quick thoughts:

The package is looking really good. Your recent work is greatly appreciated! You've done some of the heavy lifting so thanks. Ideas I had include:

- Set all options as env vars, not options. I think we talked about this and have an Isssue filed at #16 so this is 👍 
- Make rt_login() handle all login scenarios, and not separate into interactive and non-interactive versions:

Instead of two functions, what do you think about having one that:

1. Knows whether it's interactive (via `interactive()`) and:
    - If interactive
      - If login/pass given: logs in
      - If login/pass _not_ given: asks
    - If non-interactive
      - If login/pass given: logs in
      - If login/pass _not_ given: Errors

    I think this is nice as it reduces complexity while doing reasonable default behavior most of the time. And it's always overridable if you just provide your info.

- rename `rt_api` class to `rt_response` for pedantic reasons
- make sure we have handy print methods in place for `rt_api` objects. I think these are in but I haven't looked. A call to, like, `rt_ticket_search`, should print something nicely. If we need to parse more responses then so be it.
- change rt_search vignette into an rt_overview vignette and just cover the entire package in brief. The details on search can be as detailed or nearly as detailed as they are now.
- add a package-global help page, at like `?rt` with a basic intro, overlay of functions if we don't have this already
- consider removing properties suffix from rt_{ticket|user|etc}_properties for brevity

questions from looking at existing state of package

- is there a real downstream use case for the `rt_api` class? Do people want the raw URL or raw response or can we default to more sensible base R classes instead of a specialized one?

I still want to run some of the code as I haven't run things in a while so I hope to do that this week.

**Comment by mbjones** [comment]
I did a quick review of the package as well.  Looks awesome.  The only thing I'd add to Bryce's list is that there are no tests in the testthat directory.  Before a release to CRAN, I would expect at least minimal code coverage for tests in the package.  So:

- Add tests for major functions to testthat, possibly using mocks for network dependent tests

**Comment by amoeba** [comment]
Agreed! vcr just got httr support so that should be pretty doable. Issue for the work is #14

**Comment by isteves** [comment]
Good to hear about vcr!  Good chance to try it out.

1. Sounds like a good plan re: interactive/not.  `usethis::create_project()` may be a good example to work off of
2. I don't mind the change to `rt_response` but I basically took that (and the rest of the code for that section) from the [`httr` vignette](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html)
3. Print methods live [here](https://github.com/NCEAS/rt/blob/bcce00fab5a3b1e6edf7eaa0f7da484e6d1d718a/R/rt.R#L101)
4. Sounds good to me.  I'd originally intended to have additional vignettes but never got around to it...so I guess we'll stick with just that for now!  😁 
5. Package help page lives [here](https://github.com/NCEAS/rt/blob/master/R/rt_package.R) (but maybe needs to be renamed to make it more obvious?)
6. To match the API, perhaps it's better to keep it?  Though I agree that it's long and clunky.  At the very least, we should probably group them with related functions using `@family` or `@seaalso`
7. Fair question about the rt_api.  I pretty much just did it because of the `httr` vignette, but normally I would also avoid creating new classes.  I don't have strong opinions on this, so I could be persuaded either way!

**Comment by amoeba** [comment]
Great, thanks for dropping some notes in here.

Re: `rt_api` vs `rt_resposne`, let's just stick with your `rt_api` name. I'm glad you based your work off of https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html. No need to get crazy here!

> To match the API, perhaps it's better to keep it?

Yeah, I'm such a flip flopper. Would you laugh too hard if I switched them back to their long form? I'm also all for @family and @seealsos. 👍 

Looks like half of my things are non-things because you already diligently did them. Awesome! I can totally do all of this since I know you're busy but did you feel overly inclined to take on any of it?

**Comment by isteves** [comment]
@amoeba I see that you've started small changes in various places on your branch, so how about you let me know when you're done with that and I'll review/make additional changes after?  I would really like to redo the roxygen so that it's DRY.  Since that inevitably involves making changes to all files, I'm worried about entering merge conflict hell if we do stuff simultaneously.  (If my concerns are unsubstantiated, just tell me and I'll start making changes!)

**Comment by amoeba** [comment]
Updating roxygen docs collaboratively is definitely merge conflict hell! I'll wrap those changes up now and merge so you can branch off my changes.

**Comment by amoeba** [comment]
Making progress. Not quite done.

**Comment by isteves** [comment]
Yay!!  Sorry I've been MIA on this.  But if you have changes in the pipeline, prob best not to go crazy with changes.  Have you tried vcr?

**Comment by amoeba** [comment]
No worries, it sounds like you've been quite busy!

Not yet on `vcr` but I may end up adding that in. The tests so far have been hitting a live RT install and I'll need to factor that out before going to CRAN.

**Comment by amoeba** [comment]
Hey all, I've taken some time this last week or so to catch up on the backlog of tasks with an eye towards doing a release soon. I think the package is essentially ready to go.

I've been doing my work in the [cleanup](https://github.com/NCEAS/rt/tree/cleanup) branch if you wanna take a look. Some notable changes include:

- Did a pass over all documentation, including vignettes. Things should be uniform and more filled in.
- Refactored return types on many functions to types that are pipe-able (i.e., ticket functions return the ticket ID, etc).
- Set up GitHub Actions as a CI to both run `R CMD CHECK` on multiple platforms and also all tests.
- The tests are now split into unit and integration tests. The unit tests always run but the integration tests (which depend on having access to a running RT install) only when when requested (See readme).

I've also gone through the work of running `rhub::check_on_windows()`, `rhub::check_for_cran` and `goodpractice::gp()` (Thanks @gothub for the pointers) so I think this is CRAN-ready.

@isteves, @mbjones would either of you like to have a look through prior to submission?

**Comment by irenetlv** [comment]
@amoeba amazing work!  I browsed through the changes, and all the updates look 💯.  The tests look quite comprehensive, and I learned a lot by reading through your testthat files and GH Actions examples. 

From my perspective, you can go ahead and submit! :shipit:

**Comment by isteves** [comment]
@amoeba amazing work!  I browsed through the changes, and all the updates look 💯.  The tests look quite comprehensive, and I learned a lot by reading through your testthat files and GH Actions examples. 

From my perspective, you can go ahead and submit! :shipit:

**Comment by amoeba** [comment]
Thanks @isteves ! And thanks for all the help getting this package going in the first place.

**Comment by amoeba** [comment]
Closing as initial release is done.
